config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  resources :static_pages
  resources :gossips do
    resources :comments
  end
  resources :users
  resources :cities

  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'
  get '/welcome/', to: 'static_pages#welcome'
  get '/welcome/:anything', to: 'static_pages#welcome'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :gossips, through: :users

  validates :name,
  presence: true

  validates :zip_code,
  presence: true,
  uniqueness: true,
  format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip

  validates :content,
  presence: true

  validates :user_id,
  presence: true

  validates :gossip_id,
  presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :tag_gossip_links
  has_many :tags, through: :tag_gossip_links
  has_many :comments

  validates :title,
  presence: true,
  length: { in: 3..14 }

  validates :content,
  presence: true

end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :recipient_to_pm_links, foreign_key: 'received_message_id'
  has_many :recipients, foreign_key: 'recipient_id', class_name: "User", through: :recipient_to_pm_links
end

app/models/recipient_to_pm_link.rb
class RecipientToPmLink < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :received_message, class_name: "PrivateMessage"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_gossip_links
  has_many :gossips, through: :tag_gossip_links

  validates :title,
  presence: true,
  uniqueness: true
end

app/models/tag_gossip_link.rb
class TagGossipLink < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :recipient_to_pm_links, foreign_key: 'recipient_id'
  has_many :received_messages, foreign_key: 'received_message_id', class_name: "PrivateMessage", through: :recipient_to_pm_links

  validates :email,
  presence: true,
  uniqueness: true,
  format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Mauvais format" }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def show
    @city = City.find(params[:id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
     @comment = Comment.new(content:params[:content], user_id:170, gossip_id:params[:id])
     if @comment.save
         redirect_to gossip_path(params[:id])
     else
         render "new"
     end
   end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def show
    @gossip = Gossip.find(params[:id])
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(title:params[:title], content:params[:content], user_id:170) # avec xxx qui sont les données obtenues à partir du formulaire

    if @gossip.save # essaie de sauvegarder en base @gossip
      redirect_to '/'
      # si ça marche, il redirige vers la page d'index du site
    else
      # sinon, il render la view new (qui est celle sur laquelle on est déjà)
      render 'new'
    end

  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])

    if @gossip.update(gossip_params)
      redirect_to @gossip
    else
      render :edit
    end

  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to root_path
  end

  private

  def gossip_params
    params.require(:gossip).permit(:title, :content)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
    @all_gossips = Gossip.all
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @author = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Vive moi</title>
  </head>
  <body>

    <h1> Bienvenue dans la charmante ville de <b><%= @city.name %></b> </h1>

    <p>Voilà tous les potins du coin (tu ne verras plus jamais ton voisin du même oeil) :</p>

    <% @city.gossips.each do |gossip| %>
      <p>
        👉 <b><%= gossip.title %></b><br/>
        🙊 par <b><%= gossip.user.first_name %></b><br/>
      </p>

      <p>
        <%= link_to "Voir le potin", gossip_path(:id => gossip.id), class:"btn btn-primary btn-sm", role:"button" %>
        <%= link_to "Voir l'auteur", user_path(:id => gossip.user.id), class:"btn btn-primary btn-sm", role:"button" %>
      </p>

    <% end %>

  </body>
</html>

app/views/gossips/edit.html.erb
<html>
  <body>
    <!-- ... -->

    <%= form_for @gossip do |f| %>
      <div class="form-group">
        <label>Titre du gossip</label>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <label>Contenu du gossip</label>
        <%= f.text_field :content, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.submit "Modifier le potin", class:"btn btn-primary" %>
      </div>
    <% end %>


    <!-- ... -->
  </body>
</html>

app/views/gossips/new.html.erb
<html>
  <body>
    <!-- ... -->

    <% if @gossip.errors.any? %>
      <div class="alert alert-danger" role="alert">
      <p> Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
      <ul>
        <% @gossip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
      </div>
    <% end %>

    <% if @gossip.save %>
      <div class="alert alert-success" role="alert">
      <p> Success!</p>
        </div>
        <% end %>

    <%= form_tag url_for(action: 'create'), method: "post" do %>

      <%= label_tag 'Titre' %>
      <%= text_field_tag 'title', @gossip.title %>
      <br /> <br />

      <%= label_tag 'Contenu' %>
      <%= text_area_tag 'content', @gossip.content %>
      <br /> <br />

      <%= submit_tag "Create Post" %>

    <% end %>


    <!-- ... -->
  </body>
</html>

app/views/gossips/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Vive moi</title>
  </head>
  <body>

    <h1>Du potin, du potin, du potiiiin</h1>

    <h3><b> <%= @gossip.title %> </b></h3>
        <p> <%= @gossip.content %> </p>
        <p> Date de création : <%= @gossip.created_at %> </p>
        <p> Ce doss' a été lâché par <b><%= @gossip.user.first_name %></b></p>
        <p>
        <%= link_to "Voir l'auteur", user_path(:id => @gossip.user.id), class:"btn btn-primary btn-sm", role:"button" %>
        <%= link_to "Voir la ville", city_path(:id => @gossip.user.city.id), class:"btn btn-primary btn-sm", role:"button" %>
        </p>
        <p>
        <%= link_to "Modifier le potin", edit_gossip_path(:id => @gossip.id), class:"btn btn-warning btn-sm", role:"button" %>
        <%= link_to "Supprimer", @gossip, method: :delete, class:"btn btn-danger btn-sm", role:"button" %>
        </p>

        <div class="formulaire">
        <p>
          <%= form_tag url_for(controller: :comments, action: :create, id: params[:id], gossip_id: params[:id]), method: "post" do %>
          <b><%= label_tag 'Continuer à gossiper' %></b> <br>
          <%= text_field_tag 'content'%>
          <%= submit_tag 'Mytho ou pas mytho?', class:"btn btn-outline-dark btn-sm"%>
          <% end %>
        </p>
        </div>

        <p><b>Derniers commentaires</b></p>

        <% @gossip.comments.each do |comment| %>
          <p style="font-size:14px;"> <b><%= comment.user.first_name %></b> <br>
            <%= comment.content %> </p>
        <% end %>

  </body>
</html>

app/views/static_pages/contact.html.erb
<div class="row justify-content-md-center">
<h1>Nous contacter</h1>
</div>

<div class="row justify-content-md-center">
<iframe width="560" height="315" src="https://www.youtube.com/embed/QQSYo_pC-QA?start=5" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

app/views/static_pages/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>GOSSIP PROJECT</title>
  </head>
   
<body>

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">DERNIERS GOSSIP </h1>
    <p class="lead">Regardez ce qui se dit sur vous...</p>
    <a class="btn btn-warning" href="/gossips/new/" role="button">LACHE TON GOSSIP</a>
  </div>
</div>


<div class="row">
  <% @all_gossips.each do |select| %>
  <div class="col-sm-6" style="padding: 30px">
      <div class="card">
        <div class="card-header">
          <b><%= select.title %></b><br/>
          </div>
        <div class="card-body">
          <h5 class="card-title">A été écrit par <b><%= select.user.first_name %></b><br/>
          <%= link_to "Voir le potin", gossip_path(:id => select.id), class:"btn btn-primary btn-sm", role:"button" %>
    </p>
          </div>
      </div>
    </div>
  <% end %>
  </div>

  </body>
</html>

app/views/static_pages/team.html.erb
<div class="container">
    <div class="row justify-content-md-center">
        <h1>La team</h1>
    </div>
    <div class="row justify-content-md-center">
    <img src="https://scontent-cdg2-1.xx.fbcdn.net/v/t1.0-9/44458546_10156810242234708_5243389567804899328_n.jpg?_nc_cat=100&_nc_ht=scontent-cdg2-1.xx&oh=15cfb629c3e8b63c5ea9745e91a9e2c6&oe=5D2D72BF" class="img-fluid" alt="Responsive image">
    </div>
</div>

app/views/static_pages/welcome.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Vive moi</title>
  </head>
  <body>

    <h1>Hello you</h1>

  </body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Vive moi</title>
  </head>
  <body>

    <h1> Haaave you met <b><%= @author.first_name %></b> ?</h1>

      <p>Last name : <%= @author.last_name %> </p>
      <p>Description : <%= @author.description %> </p>
      <p>Email : <%= @author.email %> </p>
      <p>Age : <%= @author.age %> ans</p>
      <p>Ville : <%= @author.city.name %> </p>

      <p>
        <%= link_to "Voir la ville", city_path(:id => @author.city.id), class:"btn btn-primary btn-sm", role:"button" %>
      </p>

  </body>
</html>